### ISSUE TITLE
Issue in access api

### ISSUE THREAD

**Issue by itranga** [ajay2507/ebay-node-api#23]
const Ebay = require("ebay-node-api");

let ebay = new Ebay({
    clientID: "",
    clientSecret: '',
    body: {
        grant_type: "client_credentials"
    }
});
ebay.getAccessToken().then((data) => {
    ebay.searchItems({
        keyword: "drone",
        limit: "3"
    }).then((data) => {
        console.log(data);
    })
}, (error) => {
    console.log(error);
});

Issue

{"errors":[{"errorId":1100,"domain":"ACCESS","category":"REQUEST","message":"Access denied","longMessage":"Insufficient permissions to fulfill the request."}]}

**Comment by ajay2507** [comment]
@itranga  Are you passing the correct client ID and client secret ?.
It's working and I am getting the output https://jsoneditoronline.org/?id=1a5b88540f6e472393ec57e1a3b360b7

**Comment by sbchens88** [comment]
@ajay2507 Have the same problem, verified client ID and client secret

**Comment by ajay2507** [comment]
@sbchens88  Have to include scope to access this api, try to include scope like below

```javascript
let ebay = new Ebay({
    clientID: "",
    clientSecret: '',
    body: {
        grant_type: "client_credentials",
        scope: 'https://api.ebay.com/oauth/api_scope'
    }
});

```

**Comment by sbchens88** [comment]
Works! thank you! @ajay2507

**Comment by ajay2507** [comment]
closing this issue.

**Comment by m2jobe** [comment]
Could you please add this in the readme?
