### ISSUE TITLE
 Cannot find module 'make-string'

### ISSUE THREAD

**Issue by pythoncreate** [ajay2507/ebay-node-api#28]
not sure if i'm doing this correctly but i'm getting the following error:

`Error: Cannot find module 'make-string'`

here is my code:

```
const express = require("express");
const router = express.Router();
const Todo = require("../models/todo");
let eBay = require("ebay-node-api");

let ebay = new eBay({
  clientID: "xxxxxxxx",
  body: {
    grant_type: "client_credentials",
    scope: "https://api.ebay.com/oauth/api_scope"
  }
});

router.get("/todos", (req, res, next) => {
  //this will return all the data, exposing only the id and action field to the client
  ebay.findItemsByKeywords("iphone").then(
    data => {
      console.log(data);
    },
    error => {
      console.log(error);
    }
  );
});

module.exports = router;

```

any ideas?

**Comment by ajay2507** [comment]
@pythoncreate I will include the dependency and publish new version. As of now, you can manually install the module. It will work.
`npm install make-string`

**Comment by pythoncreate** [comment]
ok thanks!  I did do that... now when i run the get request, it's hanging on me, and showing 'undefined...any idea what might be wrong?

```
Server running on port 5000
Database connected successfully
{ clientID: 'xxxxx',
  limit: 10,
  env: 'PROD',
  baseUrl: 'api.ebay.com',
  baseSvcUrl: 'svcs.ebay.com',
  globalID: 'EBAY-US',
  name: 'iphone',
  operationName: 'findItemsByKeywords',
  param: 'keywords' }
undefined
[ { ack: [ 'Success' ],
    version: [ '1.13.0' ],
    timestamp: [ '2019-02-07T16:37:48.940Z' ],
    searchResult: [ [Object] ],
    paginationOutput: [ [Object] ],
    itemSearchURL:
     [ 'http://www.ebay.com/sch/i.html?_nkw=iphone&_ddo=1&_ipg=10&_pgn=1' ] } ]
{ clientID: 'Christop-cards-PRD-4a6d6c794-5ea59d03',
  limit: 10,
  env: 'PROD',
  baseUrl: 'api.ebay.com',
  baseSvcUrl: 'svcs.ebay.com',
  globalID: 'EBAY-US',
```

**Comment by ajay2507** [comment]
@pythoncreate  I think you are getting the proper response. you need to extract the searchResult from the JSON.
`[ { ack: [ 'Success' ],
    version: [ '1.13.0' ],
    timestamp: [ '2019-02-07T16:37:48.940Z' ],
    searchResult: [ [Object] ],
    paginationOutput: [ [Object] ],
    itemSearchURL:
     [ 'http://www.ebay.com/sch/i.html?_nkw=iphone&_ddo=1&_ipg=10&_pgn=1' ] } ]`

**Comment by ajay2507** [comment]
fix https://github.com/ajay2507/ebay-node-api/pull/29
