### ISSUE TITLE
Error: ReferenceError: dataString is not defined

### ISSUE THREAD

**Issue by daveybrown** [ajay2507/ebay-node-api#31]
Hi I get the following error when trying to get access token.

```
ReferenceError: dataString is not defined
at postRequest (/usr/app/node_modules/ebay-node-api/src/request.js:36:38)
at Ebay.getAccessToken (/usr/app/node_modules/ebay-node-api/src/index.js:87:16)
```

I fixed it by adding `let dataString = false;` above `methodName == "POST" ? dataString = qs.stringify(data) : '';` in [request.js](https://github.com/ajay2507/ebay-node-api/blob/master/src/request.js).

If this is an acceptable fix, please let me know and I'll create a pull request.

Thanks :)

**Comment by ajay2507** [comment]
@daveybrown Thanks for reporting it. dataString is a string.
so you can keep
```javascript
let dataString = '';
```
you can create pull request for this.

**Comment by ajay2507** [comment]
Fixed.

**Comment by nizanjum** [comment]
Where should i pass this dataString?

Please find below my code.. I am getting the same error

        let dataString = '';
	ebay.getAccessToken()
	    .then((data) => {
	        console.log(data);
	    }, (error) => {
	    	console.log(error);
	});

**Comment by ajay2507** [comment]
@nizanjum I have pubhlised a new version(2.5.4), install it again using below command and try
`
npm install ebay-node-api
`
