### ISSUE TITLE
Mixed Content Issue. NPM is not working with https apps.  The pagewas loaded over HTTPS, but requested an insecure resource

### ISSUE THREAD

**Issue by civilizador** [ajay2507/ebay-node-api#34]
Hello dear community.
My app is functioning over https since it's working with user's location. 
How I can achieve your library to make calls on https not http api's ?
What I get now is:
 Mixed Content: The page at ... was loaded over HTTPS, but requested an insecure resource 'http://svcs.sandbox.ebay.com/services/search/FindingService/v1?SECURITY-APPNAME=...'. This request has been blocked; the content must be served over HTTPS.

Thanks a lot!

**Comment by ajay2507** [comment]
@civilizador  Fixed. Try installing new version ebay-node-api@2.5.5

**Comment by ajay2507** [comment]
Fix https://github.com/ajay2507/ebay-node-api/commit/307016f92af7e59aa0d2afe830f8bc9be6cb497b. Closing this.
